version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper1'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2182:2181'

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-broker1'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - '9093:9092'
    depends_on:
      - zookeeper
